// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kardolus/chatgpt-cli/agent/core (interfaces: Runner)

// Package react_test is a generated GoMock package.
package react_test

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/kardolus/chatgpt-cli/agent/types"
)

// MockRunner is a mock of Runner interface.
type MockRunner struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerMockRecorder
}

// MockRunnerMockRecorder is the mock recorder for MockRunner.
type MockRunnerMockRecorder struct {
	mock *MockRunner
}

// NewMockRunner creates a new mock instance.
func NewMockRunner(ctrl *gomock.Controller) *MockRunner {
	mock := &MockRunner{ctrl: ctrl}
	mock.recorder = &MockRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunner) EXPECT() *MockRunnerMockRecorder {
	return m.recorder
}

// RunStep mocks base method.
func (m *MockRunner) RunStep(arg0 context.Context, arg1 types.Config, arg2 types.Step) (types.StepResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunStep", arg0, arg1, arg2)
	ret0, _ := ret[0].(types.StepResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunStep indicates an expected call of RunStep.
func (mr *MockRunnerMockRecorder) RunStep(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunStep", reflect.TypeOf((*MockRunner)(nil).RunStep), arg0, arg1, arg2)
}
