// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kardolus/chatgpt-cli/api/client (interfaces: MCPTransport)

// Package client_test is a generated GoMock package.
package client_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	api "github.com/kardolus/chatgpt-cli/api"
)

// MockMCPTransport is a mock of MCPTransport interface.
type MockMCPTransport struct {
	ctrl     *gomock.Controller
	recorder *MockMCPTransportMockRecorder
}

// MockMCPTransportMockRecorder is the mock recorder for MockMCPTransport.
type MockMCPTransportMockRecorder struct {
	mock *MockMCPTransport
}

// NewMockMCPTransport creates a new mock instance.
func NewMockMCPTransport(ctrl *gomock.Controller) *MockMCPTransport {
	mock := &MockMCPTransport{ctrl: ctrl}
	mock.recorder = &MockMCPTransportMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMCPTransport) EXPECT() *MockMCPTransportMockRecorder {
	return m.recorder
}

// Call mocks base method.
func (m *MockMCPTransport) Call(arg0 string, arg1 api.MCPMessage) (api.MCPMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Call", arg0, arg1)
	ret0, _ := ret[0].(api.MCPMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Call indicates an expected call of Call.
func (mr *MockMCPTransportMockRecorder) Call(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Call", reflect.TypeOf((*MockMCPTransport)(nil).Call), arg0, arg1)
}
