Output vhs.gif

Set FontSize 15
Set Shell "bash"
Set Width 680
Set Height 460
Set Theme "Tomorrow Night Bright"

Type "chatgpt what is the capital of the Netherlands?"
Enter
Sleep 2s

Type "cat README.md | chatgpt introduce this program in 1 line"
Enter
Sleep 3s

Type "git diff | chatgpt -n -p ../prompts/create_git_diff_commit.md"
Enter
Sleep 3s

Type "chatgpt --image ~/Desktop/google.png Whats in this image?"
Enter
Sleep 3s