// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kardolus/chatgpt-cli/agent/tools (interfaces: Files)

// Package core_test is a generated GoMock package.
package core_test

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	tools "github.com/kardolus/chatgpt-cli/agent/tools"
)

// MockFiles is a mock of Files interface.
type MockFiles struct {
	ctrl     *gomock.Controller
	recorder *MockFilesMockRecorder
}

// MockFilesMockRecorder is the mock recorder for MockFiles.
type MockFilesMockRecorder struct {
	mock *MockFiles
}

// NewMockFiles creates a new mock instance.
func NewMockFiles(ctrl *gomock.Controller) *MockFiles {
	mock := &MockFiles{ctrl: ctrl}
	mock.recorder = &MockFilesMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFiles) EXPECT() *MockFilesMockRecorder {
	return m.recorder
}

// PatchFile mocks base method.
func (m *MockFiles) PatchFile(arg0 string, arg1 []byte) (tools.PatchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PatchFile", arg0, arg1)
	ret0, _ := ret[0].(tools.PatchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PatchFile indicates an expected call of PatchFile.
func (mr *MockFilesMockRecorder) PatchFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PatchFile", reflect.TypeOf((*MockFiles)(nil).PatchFile), arg0, arg1)
}

// ReadFile mocks base method.
func (m *MockFiles) ReadFile(arg0 string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFile", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFile indicates an expected call of ReadFile.
func (mr *MockFilesMockRecorder) ReadFile(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFile", reflect.TypeOf((*MockFiles)(nil).ReadFile), arg0)
}

// ReplaceBytesInFile mocks base method.
func (m *MockFiles) ReplaceBytesInFile(arg0 string, arg1, arg2 []byte, arg3 int) (tools.ReplaceResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceBytesInFile", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(tools.ReplaceResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceBytesInFile indicates an expected call of ReplaceBytesInFile.
func (mr *MockFilesMockRecorder) ReplaceBytesInFile(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceBytesInFile", reflect.TypeOf((*MockFiles)(nil).ReplaceBytesInFile), arg0, arg1, arg2, arg3)
}

// WriteFile mocks base method.
func (m *MockFiles) WriteFile(arg0 string, arg1 []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockFilesMockRecorder) WriteFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockFiles)(nil).WriteFile), arg0, arg1)
}
